#!/bin/bash

SCRIPTS_DIR="/usr/local/bin/chromex_scripts"

print_help() {
  echo "Usage: $0 <subcommand> [options]"
  echo ""
  echo "Subcommands:"
  echo "  init           Initialize a new Chrome extension project"
  echo "  manifest       Add or remove properties in the manifest.json file"
  echo ""
  echo "For help with each subcommand, run:"
  echo "$0 <subcommand> --help"
}

if [ "$#" -eq 0 ]; then
  print_help
  exit 1
fi

SUBCOMMAND="$1"
shift

case "$SUBCOMMAND" in
  init)
    "$SCRIPTS_DIR/init_chrome_extension.sh" "$@"
    ;;
  manifest)
    "$SCRIPTS_DIR/modify_manifest.sh" "$@"
    ;;
  toggle)
    "$SCRIPTS_DIR/toggle_sites.sh" "$@"
    ;;
  # Add more subcommands below
  *)
    echo "Error: Unknown subcommand '$SUBCOMMAND'"
    print_help
    exit 1
    ;;
esac
